# .streamlit/secrets.toml

[snowflake]
user = "BILLMATTERN"
password = "****"
account = "yub65960.us-east-1"
warehouse = "Compute_wh"
database = "BI"
schema = "ETL"


[snowflake1]
user = "Peter2023"
password = "****"
account = "dab47500.us-east-1"
warehouse = "Compute_wh"


[snowflake2]
user = "VIBE1"
password = "****"
account = "af09684.central-us.azure"
warehouse = "Compute_wh"


[snowflake3]
user = "JUSTIN"
password = "******"
account = "ir45464.east-us-2.azure"
warehouse = "Compute_wh"
database = "TRIAL_123"
schema = "PUBLIC"


[snowflake4]
user = "James01"
password = "******"
account = "dta66607.east-us-2.azure"
warehouse = "Compute_wh"
database = "TRIAL_123"
schema = "PUBLIC"

